Repository Circus-Group-Project/TheBrosBlogSite, pull requests merged in 2023-06, with the labels that each got.

#1 Added Home Page
  blogsite/package-lock.json
  blogsite/package.json
  blogsite/src/App.css
  blogsite/src/App.js
  blogsite/src/App.test.js
  blogsite/src/components/footer/Footer.css
  blogsite/src/components/footer/Footer.js
  blogsite/src/components/home/home.css
  blogsite/src/components/home/home.js
  blogsite/src/components/navbar/Navbar.css
  blogsite/src/components/navbar/Navbar.js
  blogsite/src/index.css
  blogsite/src/index.js
  blogsite/src/logo.svg
  blogsite/src/reportWebVitals.js
  blogsite/src/setupTests.js
Labels: enhancement

#2 Update README.md
  README.md
Labels: documentation

#6 Added Gallery View Section
  blogsite/src/components/gallery/Gallery.css
  blogsite/src/components/gallery/Gallery.js
Labels: enhancement

#8 fix upload responsiveness on laptop screens
  blogsite/src/components/upload/Upload.css
  blogsite/src/components/upload/Upload.js
Labels: feature

#9 Added Profile Page
  blogsite/package-lock.json
  blogsite/src/components/login/Login.js
  blogsite/src/components/profile/Profile.css
  blogsite/src/components/profile/Profile.js
  blogsite/src/index.js
  blogsite/src/routes/ProfilePage.js
Labels: enhancement

#10 add new css and structure for profile
  blogsite/src/App.js
  blogsite/src/components/profile/Profile.css
  blogsite/src/components/profile/Profile.js
Labels: enhancement

#11 added functionality to gallery page
  blogsite/src/App.js
  blogsite/src/components/gallery/Gallery.js
Labels: enhancement

#12 Add routing to new page
  blogsite/src/components/gallery/Gallery.js
  blogsite/src/components/gallery/GalleryDisplay.css
  blogsite/src/components/gallery/GalleryDisplay.js
  blogsite/src/index.js
  blogsite/src/routes/GalleryDisplayPage.js
Labels: enhancement

#13 added display for each gallery
  Server/src/main/java/com/example/server/ServerApplication.java
  blogsite/src/components/gallery/GalleryDisplay.css
  blogsite/src/components/gallery/GalleryDisplay.js
  blogsite/src/index.css
Labels: feature

#14 Rework some components
  blogsite/src/components/footer/Footer.js
  blogsite/src/components/gallery/GalleryDisplay.js
  blogsite/src/components/navbar/Navbar.js
  blogsite/src/components/navbar/NavbarDisplay.js
  blogsite/src/routes/GalleryDisplayPage.js
Labels: enhancement

#15 rework and fix upload based on sugggestions
  blogsite/src/components/gallery/GalleryDisplay.js
  blogsite/src/components/upload/Upload.css
  blogsite/src/components/upload/Upload.js
  blogsite/src/index.css
  blogsite/src/routes/GalleryDisplayPage.js
Labels: enhancement

#16 added functionality to store form input into consolelog
  blogsite/src/components/upload/Upload.js
Labels: feature

#17 Routing Based on Authentication
  blogsite/src/AuthContext.js
  blogsite/src/components/login/Login.js
  blogsite/src/components/navbar/Navbar.js
  blogsite/src/index.js
Labels: enhancement

#18 add fitlers to gallery
  blogsite/src/components/gallery/Gallery.css
  blogsite/src/components/gallery/Gallery.js
  blogsite/src/components/gallery/GalleryDisplay.js
  blogsite/src/components/login/Login.js
  blogsite/src/components/upload/Upload.js
Labels: feature
